spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mytest?characterEncoding=UTF-8&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    sql-script-encoding: UTF-8
    continue-on-error: false
    platform: mysql
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      pool-name: DatebookHikariCP
      connection-test-enums: SELECT 1
    type: com.zaxxer.hikari.HikariDataSource
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: false
    show-sql: true
    open-in-view: true
    #    properties:
    #      hibernate:
    #        enable_lazy_load_no_trans: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
